[masters]
192.168.0.200

[masters:vars]
db_folder=sqlite
db_file=db.sqlite
master_api_key="MY_MASTER_API_KEY"

[slaves_group_1]
192.168.0.201
[slaves_group_1:vars]
db_folder=sqlite
db_file=db.sqlite
master_ip="192.168.0.200"

[slaves_group_2]
192.168.0.202
[slaves_group_2:vars]
db_folder=sqlite
db_file=db.sqlite
master_ip="192.168.0.200"
