---
# this playbook uses https://github.com/PowerDNS/pdns-ansible.git

# Masters definition

- hosts: masters
  roles:
    - { role: PowerDNS.pdns }
  vars:
    pdns_config:
      master: true
      slave: false
      local-address: "{{ ansible_all_ipv4_addresses }}"
      prevent-self-notification: true
      api: yes
      api-key: "{{ master_api_key }}"
    pdns_backends:
      gpgsql:
        gpgsql-host: "{{ database_host }}"
        gpgsql-dbname: "{{ database_name }}"
        gpgsql-user: "{{ database_user }}"
        gpgsql-password: "{{ database_password }}"
        gpgsql-extra-connection-parameters: "{{ database_extra }}"
        dnssec: false

# Slave/s definition

# Slave Server Set A

- hosts: slaves
  roles:
    - { role: PowerDNS.pdns }
    - { role: sqlite_slave_insert }
  vars:
    master_ip: "192.168.0.200"
    pdns_config:
      master: false
      slave: true
      superslave: true
      allow-axfr-ips: "{{ master_ip }}"
      allow-notify-from: "{{ master_ip }}"
      local-address: "{{ ansible_all_ipv4_addresses }}"
    pdns_backends:
      gsqlite3:
        database: "/var/lib/powerdns/db.sqlite"
        dnssec: false

# Slave Server Set B

#- hosts: 1.2.3.4, 1.2.3.5
#  roles:
#    - { role: PowerDNS.pdns }
#    - { role: sqlite_slave_insert }
#  vars:
#    master_ip: "1.4.5.3"
#    pdns_config:
#      master: false
#      slave: true
#      superslave: true
#      local-address: "{{ ansible_all_ipv4_addresses }}"
#    pdns_backends:
#      gsqlite3:
#        database: "/var/lib/powerdns/db.sqlite"
#        dnssec: false
