# this playbook uses https://github.com/PowerDNS/pdns-ansible.git
# Masters definition

- hosts: masters
  roles:
    - { role: preinstall }
    - { role: sqlite_master_config }
    - { role: PowerDNS.pdns }
    - { role: poweradmin }
  vars:    
    pdns_package_version: "4.4.0"
    pdns_config:
      master: true
      slave: false
      local-address: "{{ ansible_all_ipv4_addresses }}"
      prevent-self-notification: true
      api: yes
      api-key: "{{ master_api_key }}"
      allow-axfr-ips: "192.168.0.198,192.168.0.200,192.168.0.201,192.168.0.202"
    pdns_service_state: "started"
    pdns_service_enabled: "yes"
    pdns_backends:
      gsqlite3:
        database: "/{{ db_folder }}/{{ db_file }}"
        dnssec: false

# Slave/s definition
# Slave Server Set A

- hosts: slaves_group_1,slaves_group_2
  roles:
    - { role: preinstall }
    - { role: PowerDNS.pdns }
    - { role: sqlite_slave_config }
  vars:
    pdns_config:
      master: false
      slave: true
      superslave: true
      allow-axfr-ips: "{{ master_ip }},192.168.0.0/24"
      allow-notify-from: "{{ master_ip }}"
      local-address: "{{ ansible_all_ipv4_addresses }}"
    pdns_backends:
      gsqlite3:
        database: "/{{ db_folder }}/{{ db_file }}"
        dnssec: false
