# this playbook uses https://github.com/PowerDNS/pdns-ansible.git

# Masters definition

- hosts: 192.168.0.200
  roles:
    - { role: PowerDNS.pdns }
  vars:
    pdns_config:
      master: true
      slave: false
      local-address: "{{ ansible_all_ipv4_addresses }}"
      prevent-self-notification: true
    pdns_backends:
      gpgsql:
        gpgsql-dbname: "pdns"
        gpgsql-host: "192.168.0.200"
        gpgsql-user: "pdns"
        gpgsql-password: "YOUR_DB_PASS_HERE"
        gpgsql-extra-connection-parameters: ""
        dnssec: false

# Slave/s definition

- hosts: 192.168.0.201, 192.168.0.202
  roles:
    - { role: PowerDNS.pdns }
    - { role: sqlite_slave_insert }
  vars:
    master_ip: "192.168.0.200"
    pdns_config:
      master: false
      slave: true
      superslave: true
      local-address: "{{ ansible_all_ipv4_addresses }}"
    pdns_backends:
      gsqlite3:
        database: "/var/lib/powerdns/db.sqlite"
        dnssec: false

