# this playbook uses https://github.com/PowerDNS/pdns-ansible.git
# Masters definition

- hosts: masters
  roles:
    - { role: preinstall }
    - { role: PowerDNS.pdns }
  vars:
    pdns_config:
      master: true
      slave: false
      local-address: "{{ ansible_all_ipv4_addresses }}"
      prevent-self-notification: true
      api: yes
      api-key: "{{ master_api_key }}"
    pdns_backends:
      gpgsql:
        host: "{{ database_host }}"
        dbname: "{{ database_name }}"
        user: "{{ database_user }}"
        password: "{{ database_password }}"
        dnssec: false

# Slave/s definition

# Slave Server Set A

- hosts: slaves_group_1,slaves_group_2
  roles:
    - { role: preinstall }
    - { role: PowerDNS.pdns }
    - { role: sqlite_slave_config }
  vars:
    pdns_config:
      master: false
      slave: true
      superslave: true
      allow-axfr-ips: "{{ master_ip }}"
      allow-notify-from: "{{ master_ip }}"
      local-address: "{{ ansible_all_ipv4_addresses }}"
    pdns_backends:
      gsqlite3:
        database: "/{{ db_folder }}/{{ db_file }}"
        dnssec: false