- name: Create  {{ db_folder }}directory if it does not exist
  file:
    path: /{{ db_folder }}
    state: directory
    mode: '0755'

- name: Configure the SQL schema file for master
  template:
    src: schema.sqlite3.sql.template
    dest: /{{ db_folder }}/schema.sqlite3.sql

- name: Configure the SQL schema file to fix change_date error
  template:
    src: change_date_schema_fix.sql.template
    dest: /{{ db_folder }}/change_date_schema_fix.sql

- name: Stat Sqlite DB 
  stat:
    path: /{{ db_folder }}/{{ db_file }}
  register: SQLITEDB

- name: Stat Sqlite DB dir
  stat:
    path: /{{ db_folder }}
  register: SQLITEDB_DIR

- name: One Time SQL load of SQLite Schema
  shell: "sqlite3 /{{ db_folder }}/{{ db_file }} < /{{ db_folder }}/schema.sqlite3.sql && sqlite3 /{{ db_folder }}/{{ db_file }} < /{{ db_folder }}/change_date_schema_fix.sql && chown -R pdns:apache /{{ db_folder }}"
  when: SQLITEDB_DIR.stat.exists and not SQLITEDB.stat.exists

- name: Stat Sqlite DB 
  stat:
    path: /{{ db_folder }}/{{ db_file }}
  register: SQLITEDB
